#!/usr/bin/env python3
# Copyright (C) 2016 The OpenTimestamps developers
#
# This file is part of the OpenTimestamps Client.
#
# It is subject to the license terms in the LICENSE file found in the top-level
# directory of this distribution.
#
# No part of the OpenTimestamps Client, including this file, may be copied,
# modified, propagated, or distributed except according to the terms contained
# in the LICENSE file.

import logging
import sys

# Convert v0 timestamp files to v1

with open(sys.argv[1], 'r+b') as fd:
    magic = fd.read(31)

    version = fd.read(1)
    assert version == b'\x00'

    old_digest_len = fd.read(1)[0]
    digest = fd.read(old_digest_len)
    file_hash_op = fd.read(1)

    rest = fd.read()

    fd.truncate(0)
    fd.seek(0)

    fd.write(magic)
    fd.write(b'\x01') # new version
    fd.write(file_hash_op)
    fd.write(digest)

    fd.write(rest)

# vim:syntax=python filetype=python
