#!/usr/bin/python
#
# Copyright (C) 2012 Peter Todd <pete@petertodd.org>
#
# This file is part of the OpenTimestamps Client.
#
# It is subject to the license terms in the LICENSE file found in the top-level
# directory of this distribution and at http://opentimestamps.org
#
# No part of the OpenTimestamps Client, including this file, may be copied,
# modified, propagated, or distributed except according to the terms contained
# in the LICENSE file.

import unittest

loader = unittest.TestLoader()

suite = loader.discover('.')

runner = unittest.TextTestRunner(verbosity=2)
result = runner.run(suite)
